name: $(SourceBranchName).$(Date:yyyyMMdd)$(Rev:.r)

pr:
  - master

trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build_and_test
    displayName: Build and test
    jobs:
      - job: Build_and_test
        displayName: Build And tests
        steps:

        - task: NodeTool@0
          inputs:
            versionSpec: '12.x'
          displayName: 'Install Node.js'

        - script: |
            yarn install
            yarn lint
          displayName: 'yarn install and build'

        - script: |
            yarn test:ci
          displayName: 'Tests'

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testRunner: JUnit
            testResultsFiles: 'artifacts/*.xml'

        - script: |
            yarn run fix
            yarn run make
          displayName: 'Build'
